app = "chat-app-backend"
primary_region = "mad"  # Madrid, pero puedes elegir una región más cercana a ti

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "pb_data"
  destination = "/pb/pb_data"

[[services]]
  internal_port = 8090
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]
    
  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000  
